### ISSUE TITLE
 实验楼向您申请教程《numpy用户指南》转载授权

### ISSUE THREAD

**Issue by markiremenber** [bat67/numpy-user-guide-zh#1]
您好，

我是在线 IT 技术实训平台实验楼（https://shiyanlou.com）的课程运营何宇恒，冒昧打扰您，近期看到您写的《numpy用户指南》（链接:https://github.com/bat67/numpy-user-guide-zh），这是numpy非常优秀的教程，现想向您申请授权转载这篇文章到我们网站的教程库。

转载的教程会完全开源，在显著位置放上来源以及您的信息，如果您的教程有 Github 仓库，我们会自动同步并引导用户向您的 Github 提交 issue 或 PR 完善教程，如果没有对应的仓库会放在我们的 Github 仓库中，我们也会进行定期同步。实验楼目前有100万用户，在IT领域有一定的影响力，为了让您的教程能影响到更多的用户，特此向您申请转载授权，期待得到您的回复！

另：通过您发表的教程文章，我们相信您的技术水平。现实验楼在积极对外寻找课程合作者，我们会不定时为合作者发布课程需求，如果您愿意与我们合作制作一些优质的课程（图文形式），欢迎添加我们的微信：shiyanloukecheng

实验楼，敬上

**Comment by bat67** [comment]
您好，
非常感谢您的来信和实验楼团队的信任。这个项目是去年无聊写着玩的，后来因为事情多了，项目的后面部分并没有完全写完，也没有想到这些文章会有用武之地，若是贵平台不嫌弃目前这个烂尾作品，我会抽时间把它翻译完（或许不会很快，因为现在我还在上学）。当然要是贵平台能号召来学习的小伙伴们，或者编程爱好者等提交  issue 或 PR 完善教程，那更是感激不尽。


最后祝实验楼越办越好！






------------------ 原始邮件 ------------------
发件人: "markiremenber"<notifications@github.com>;
发送时间: 2018年10月22日(星期一) 下午3:55
收件人: "bat67/numpy-user-guide-zh"<numpy-user-guide-zh@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [bat67/numpy-user-guide-zh]  实验楼向您申请教程《numpy用户指南》转载授权 (#1)




您好，
 
我是在线 IT 技术实训平台实验楼（https://shiyanlou.com）的课程运营何宇恒，冒昧打扰您，近期看到您写的《numpy用户指南》（链接:https://github.com/bat67/numpy-user-guide-zh），这是numpy非常优秀的教程，现想向您申请授权转载这篇文章到我们网站的教程库。
 
转载的教程会完全开源，在显著位置放上来源以及您的信息，如果您的教程有 Github 仓库，我们会自动同步并引导用户向您的 Github 提交 issue 或 PR 完善教程，如果没有对应的仓库会放在我们的 Github 仓库中，我们也会进行定期同步。实验楼目前有100万用户，在IT领域有一定的影响力，为了让您的教程能影响到更多的用户，特此向您申请转载授权，期待得到您的回复！
 
另：通过您发表的教程文章，我们相信您的技术水平。现实验楼在积极对外寻找课程合作者，我们会不定时为合作者发布课程需求，如果您愿意与我们合作制作一些优质的课程（图文形式），欢迎添加我们的微信：shiyanloukecheng
 
实验楼，敬上

**Comment by bat67** [comment]
您好，

昨天GitHub似乎出了些问题，我再回复一次吧。

非常感谢您的来信和实验楼团队的信任。这个项目是去年无聊写着玩的，后来因为事情多了，项目的后面部分并没有完全写完，也没有想到这些文章会有用武之地，若贵平台不嫌弃目前这个烂尾作品，我会尽量抽时间把它写完。若贵平台能号召来学习的小伙伴们，或者编程爱好者等提交 issue 或 PR 完善教程，那更是感激不尽。 

最后祝实验楼越办越好，蒸蒸日上！

**Comment by markiremenber** [comment]
好的，非常感谢您的回复和授权！
如果能引入我们的wiki库并对您的教程作出贡献的话，我们也非常荣幸！

实验楼，敬上
